name: flatten_json
version: '0.1.0'
config-version: 2

# Optional: Add description and other metadata
description: "A package for custom macros"
package: true

# Specify your macros directory
macro-paths: ["macros"]
